title: Abdullahnz's Notes
author: Nizam Abdullah
email: edfallennzm@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Personal blog of Nizam Abdullah.
show_excerpts: true # set to true to show excerpts on the homepage
profile_image: "assets/portfolio.png"
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Nizam Abdullah
  tagline: Student.
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  html_lang: "en" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  disqus_shortname: abdullahnz
  navigation:
    - title: Categories
      url: "/categories"
  # generate social links in footer
  social_links: 
    github:  abdullahnz 
    rss: rss 
    instagram: abdullahnz_  
    facebook: profile.php?id=100006254298767 
    telegram: abdullahnzz
  

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
